# Generated by Django 5.0.2 on 2024-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Pop'), ('Jazz Music', 'Jazz'), ('R&B Music', 'Rnb'), ('Rock Music', 'Rock'), ('Country Music', 'Country'), ('Dance Music', 'Dance'), ('Hip Hop Music', 'Hip Hop'), ('Other', 'Other')], max_length=30),
        ),
    ]
